name: social_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dart_jsonwebtoken: ^2.14.0
  dartz: ^0.10.1
  device_preview: ^1.1.0
  equatable: ^2.0.5
  file_picker: ^6.2.0
  firebase_admin: ^0.2.0
  firebase_app_check: ^0.2.2+7
  firebase_auth: ^4.20.0
  firebase_core: ^2.24.2
  firebase_messaging: null
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  hexcolor: ^3.0.1
  http: ^0.13.0
  iconsax: ^0.0.8
  image_picker: ^1.0.8
  intl: ^0.18.1
  pointycastle: ^3.9.1
  quickalert: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800

  assets:
    - assets/images/
    - assets/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
