// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXLqA4dZnAPCROPfFsmHzkr6_AiTmgc8Y',
    appId: '1:625418838980:web:075f2158f5166f9355fa91',
    messagingSenderId: '625418838980',
    projectId: 'mo-social-app',
    authDomain: 'mo-social-app.firebaseapp.com',
    storageBucket: 'mo-social-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHse-pwiJt-OTauLn0SX80xwJCL6dDmg8',
    appId: '1:625418838980:android:94b605928214181955fa91',
    messagingSenderId: '625418838980',
    projectId: 'mo-social-app',
    storageBucket: 'mo-social-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2eG-rLZLH89hjfZE3MAJXwoCKXQqqQvs',
    appId: '1:625418838980:ios:9e94c1c2d09938b355fa91',
    messagingSenderId: '625418838980',
    projectId: 'mo-social-app',
    storageBucket: 'mo-social-app.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2eG-rLZLH89hjfZE3MAJXwoCKXQqqQvs',
    appId: '1:625418838980:ios:920ca248e2ba82a255fa91',
    messagingSenderId: '625418838980',
    projectId: 'mo-social-app',
    storageBucket: 'mo-social-app.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
